# array

In [1]:
# basic
import numpy as np
x=[1,2,3,4]
y=np.array(x)
print(y)

[1 2 3 4]


In [2]:
# array create with data type
import numpy as np
arr=np.array([1,2,3,4])
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [3]:
# direct
arr

array([1, 2, 3, 4])

In [4]:
# taking input and print array with append function
l=[]
for i in range(1,5):
    int_1=int(input('enter : '))
    l.append(int_1)
arr=np.array(l)
print(arr)

enter :  1
enter :  2
enter :  3
enter :  4


[1 2 3 4]


# types of aaray
# 1-D
# 2-D
# 3-D
# Higher Dimensional arrays

In [5]:
# 1-D Array
x=np.array([1,2,3,4])
print(x)
print('This is', x.ndim, 'Dimensional array')

[1 2 3 4]
This is 1 Dimensional array


In [6]:
# 2-D Array
x=np.array([[1,2,3],[4,5,6]])
print(x)
print('This is', x.ndim, 'Dimensional array')

[[1 2 3]
 [4 5 6]]
This is 2 Dimensional array


In [7]:
# 3-D array
x=np.array([[[1,2,3],[4,5,6],[6,7,8],[9,10,11]]])
print(x)
print('This is', x.ndim, 'Dimensional array')

[[[ 1  2  3]
  [ 4  5  6]
  [ 6  7  8]
  [ 9 10 11]]]
This is 3 Dimensional array


In [8]:
# 4-D array
x=np.array([1,2,3,4,5],ndmin=4)
print(x)
print('This is', x.ndim, 'Dimensional array')

[[[[1 2 3 4 5]]]]
This is 4 Dimensional array


In [9]:
# 10-D array
x=np.array([1,2,3,4,5],ndmin=10)
print(x)
print('This is', x.ndim, 'Dimensional array')

[[[[[[[[[[1 2 3 4 5]]]]]]]]]]
This is 10 Dimensional array
