# array filled with 0's
# array filled with 1's
# create an empty array
# an array with a range of elements
# array diagonal element filled with 1's
# create an array with values that are spaced linearly in a specified interval

# filled 0's

In [1]:

import numpy as np
x=np.zeros(4)
print(x)

[0. 0. 0. 0.]


In [2]:
# 2-D array with 4 rows and 3 columns
import numpy as np
x=np.zeros((4,3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# filled with 1's

In [3]:

x=np.ones(5)
print(x)

[1. 1. 1. 1. 1.]


In [4]:
# 2-D array with(3,4)
x=np.ones((3,4))
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# empty

In [5]:

x=np.empty(4)
print(x)

[0. 0. 0. 0.]


# range array(arange)

In [6]:

x=np.arange(4)
print(x)


[0 1 2 3]


In [7]:
x1=np.arange(1,5)
print(x1)

[1 2 3 4]


In [8]:
x2=np.arange(0,101,10)
print(x2)

[  0  10  20  30  40  50  60  70  80  90 100]


# diogonal array (default 2-D)

In [9]:

x=np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
# diogonal array (default 2-D) with 3 rows and 5 columns
x=np.eye(3,5)
print(x)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


# linspace function

In [11]:

x=np.linspace(1,10,num=5)
print(x)

[ 1.    3.25  5.5   7.75 10.  ]


In [12]:
x=np.linspace(0,10,num=5)
print(x)

[ 0.   2.5  5.   7.5 10. ]


In [13]:
x=np.linspace(0,20,num=5)
print(x)

[ 0.  5. 10. 15. 20.]
