# random number

# rand()

In [1]:
# using rand() and its a 1-D array and value is (0 to 1)
import numpy as np
x=np.random.rand(10)
print(x)

[0.99523893 0.97201114 0.69701989 0.47020869 0.72611049 0.913698
 0.95588582 0.58856555 0.51281933 0.52130148]


In [2]:
# creating 2-D (4,5) using rand()
x1=np.random.rand(4,5)
print(x1)

[[0.06097484 0.72241692 0.86465843 0.27956792 0.08657139]
 [0.21424272 0.98754266 0.70875421 0.32574969 0.88590433]
 [0.82996278 0.89999946 0.31999012 0.76282818 0.56214769]
 [0.82028103 0.61974432 0.96606053 0.65585564 0.73629671]]


# randn()

In [3]:
# showed positive and negative value
x=np.random.randn(10)
x

array([-0.95233107,  2.53342809,  0.4459015 ,  1.81361088,  0.96963854,
        1.67265209, -0.63855541,  0.02031232, -0.09783438, -1.22601196])

# ranf()

In [4]:
x=np.random.ranf(4)
x

array([0.49378383, 0.65336816, 0.78028578, 0.32179402])

# randint()

In [7]:
# generated random value (o to 10)
x=np.random.randint(0,10)
x

3

In [9]:
# generated random value (1 to 20) and count the random value total is 5
x=np.random.randint(1,20,5)
x

array([16, 19,  7,  5,  7])