# arithmetic operation perform

# 1-D array

In [ ]:
# add
import numpy as np
x=np.array([1,2,3,4])
add=x+3
print(add)

In [ ]:
x1=np.array([1,2,3,4])
x2=np.array([1,2,3,4])
add=x1+x2
print(add)

In [ ]:
x1=np.array([1,2,3,4])
x2=np.array([5,6,7,8])
add=x1+x2
print(add)

In [ ]:
# subtraction
import numpy as np
x=np.array([1,2,3,4])
sub=x-3
print(sub)

In [ ]:
# multiplication
import numpy as np
x=np.array([1,2,3,4])
mul=x*3
print(mul)

In [ ]:
# division
import numpy as np
x=np.array([1,2,3,4])
div=x/3
print(div)

In [ ]:
# modulus
import numpy as np
x=np.array([1,2,3,4])
mod=x%3
print(mod)

In [ ]:
# exponential
import numpy as np
x=np.array([1,2,3,4])
exp=x**3
print(exp)

In [ ]:
# another way to solve this problems
# add()
import numpy as np
x1=np.array([1,2,3,4])
x2=np.array([1,2,3,4])
x=np.add(x1,x2)
print(x)

In [ ]:
# subtract()
import numpy as np
x1=np.array([5,2,6,4])
x2=np.array([1,2,3,4])
x=np.subtract(x1,x2)
print(x)

In [ ]:
# multiply()
import numpy as np
x1=np.array([1,2,3,4])
x2=np.array([1,2,3,4])
x=np.multiply(x1,x2)
print(x)

In [ ]:
# divide()
import numpy as np
x1=np.array([1,2,3,4])
x2=np.array([1,2,3,4])
x=np.divide(x1,x2)
print(x)

In [ ]:
# mod()
import numpy as np
x1=np.array([1,2,3,4])
x2=np.array([1,2,3,4])
x=np.mod(x1,x2)
print(x)

In [ ]:
# power()
import numpy as np
x1=np.array([1,2,3,4])
x2=np.array([1,2,3,4])
x=np.power(x1,x2)
print(x)

In [ ]:
# add()
import numpy as np
x1=np.array([1,2,3,4])

x=np.add(x1,3)
print(x)

# 2D array

In [1]:
# add()
import numpy as np
x1=np.array([[1,2,3],[4,5,6]])
x2=np.array([[1,2,3],[4,5,6]])
print(x1)
print()
print(x2)
print('RESULT')
x=np.add(x1,x2)
print(x)

[[1 2 3]
 [4 5 6]]

[[1 2 3]
 [4 5 6]]
RESULT
[[ 2  4  6]
 [ 8 10 12]]


In [2]:
# multiply()
import numpy as np
x1=np.array([[1,2,3],[4,5,6]])
x2=np.array([[1,2,3],[4,5,6]])
print(x1)
print()
print(x2)
print('RESULT')
x=np.multiply(x1,x2)
print(x)

[[1 2 3]
 [4 5 6]]

[[1 2 3]
 [4 5 6]]
RESULT
[[ 1  4  9]
 [16 25 36]]


# 3D array

In [3]:
# add()
import numpy as np
x1=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
x2=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
x=np.add(x1,x2)
print(x)

[[[ 2  4  6]
  [ 8 10 12]
  [14 16 18]]]
