# shape and reshape 

# shape

In [1]:
import numpy as np
x=np.array([1,2,3,4,5,6,7,8])
print(x)
print()
print(x.shape)

[1 2 3 4 5 6 7 8]

(8,)


In [2]:
x=np.array([[1,2,3],[4,5,6]])
print(x)
print()
print(x.shape)

[[1 2 3]
 [4 5 6]]

(2, 3)


In [3]:
x=np.array([[1,2,3],[4,5,6],[1,2,3]])
print(x)
print()
print(x.shape)

[[1 2 3]
 [4 5 6]
 [1 2 3]]

(3, 3)


In [4]:
x=np.array([[1,2,3,2],[4,5,4,6],[1,2,5,3]])
print(x)
print()
print(x.shape)

[[1 2 3 2]
 [4 5 4 6]
 [1 2 5 3]]

(3, 4)


In [5]:
# multidimensional arrays shape count
x=np.array([1,2,3,4],ndmin=4)
print(x.ndim)
print(x)
print(x.shape)

4
[[[[1 2 3 4]]]]
(1, 1, 1, 4)


In [6]:
# 3D array with shape
x=np.array([[[1,2,3,4],[4,5,6,7],[4,3,2,1],[9,0,8,7]]])
print(x)
print()
print(x.shape)

[[[1 2 3 4]
  [4 5 6 7]
  [4 3 2 1]
  [9 0 8 7]]]

(1, 4, 4)


In [7]:
# 3D array with shape
x=np.array([[[1,2,3,4],[4,5,6,7],[4,3,2,1],[9,0,8,7]],[[1,2,3,4],[5,6,7,8],[1,2,3,4],[5,6,7,8]]])
print(x)
print()
print(x.shape)

[[[1 2 3 4]
  [4 5 6 7]
  [4 3 2 1]
  [9 0 8 7]]

 [[1 2 3 4]
  [5 6 7 8]
  [1 2 3 4]
  [5 6 7 8]]]

(2, 4, 4)


# reshape

In [ ]:
# 1D to 2D converted
import numpy as np
x=np.array([1,2,3,4,5,6])
print(x)
print(x.ndim)
print()
x1=x.reshape(3,2)
print(x1)
print(x1.ndim)

In [1]:

# 1D to 2D converted
import numpy as np
x=np.array([1,2,3,4,5,6])
print(x)
print(x.ndim)
print()
x1=x.reshape(2,3)
print(x1)
print(x1.ndim)

[1 2 3 4 5 6]
1

[[1 2 3]
 [4 5 6]]
2


In [2]:
# 1D to 3D converted
import numpy as np
x=np.array([1,2,3,4,5,6,7,8])
print(x)
print(x.ndim)
print()
x1=x.reshape(2,2,2)
print(x1)
print(x1.ndim)

[1 2 3 4 5 6 7 8]
1

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3


In [3]:
# 3D to 1D
import numpy as np
x=np.array([1,2,3,4,5,6,7,8])
print(x)
print(x.ndim)
print()
x1=x.reshape(2,2,2)
print(x1)
print(x1.ndim)
print()
one_dim=x1.reshape(-1)
print(one_dim)
print(one_dim.ndim)

[1 2 3 4 5 6 7 8]
1

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3

[1 2 3 4 5 6 7 8]
1
