# broadcasting

In [1]:
import numpy as np
x1=np.array([1,2,3,4])
x2=np.array([1,2,3])
print(x1+x2)

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [2]:
import numpy as np
x1=np.array([1,2,3,4])
x2=np.array([1,2,3,4])
print(x1+x2)

[2 4 6 8]


In [4]:
#[1 2 3 4] + 
#[1]
#[2]
#[3]
#[4]
#[1x4]=[4x1]===[4x4]
import numpy as np
x1=np.array([1,2,3,4])
print(x1)
print(x1.shape)
print()


x2=np.array([[1],[2],[3],[4]])
print(x2)
print(x2.shape)
print()

x=np.add(x1,x2)
print(x)

[1 2 3 4]
(4,)

[[1]
 [2]
 [3]
 [4]]
(4, 1)

[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]]


In [5]:
# [2x1]=[2x3] array matrix
x=np.array([[1],[2]])
print(x)
print(x.shape)
print()

y=np.array([[1,2,3],[1,2,3]])
print(y)
print(y.shape)
print()
add=x+y
print(add)
print(add.shape)



[[1]
 [2]]
(2, 1)

[[1 2 3]
 [1 2 3]]
(2, 3)

[[2 3 4]
 [3 4 5]]
(2, 3)
