# indexing

In [1]:
import numpy as np

In [2]:
# 1D array indexing
x=np.array([1,4,3,5,7])
print(x[2])

3


In [3]:
x=np.array([1,4,3,5,7])
print(x[-1])

7


In [4]:
x=np.array([1,4,3,5,7])
print(x[-2])

5


In [5]:
# 2D array indexing
x=np.array([[1,2,3,4],[5,6,7,8]])
print(x)
print(x.ndim)
print()
print(x[1,3]) # row then index

[[1 2 3 4]
 [5 6 7 8]]
2

8


In [6]:
# 2D array indexing
x=np.array([[1,2,3,4],[5,6,7,8]])
print(x)
print(x.ndim)
print()
print(x[0,0]) # row then index

[[1 2 3 4]
 [5 6 7 8]]
2

1


In [7]:
# 3D array indexing
x=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(x)
print(x.ndim)
print(x.shape)
print('Output :')
print(x[1,1,2])


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
(2, 2, 3)
Output :
12


In [8]:
# 3d array indexing
x=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(x)
print()
print(x[1,1,0])


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

10


# slicing

In [9]:
# 1D array slicing
import numpy as np
x=np.array([4,3,5,2,6,7])
print(x[::])
print(x[:3])
print(x[2:])
print(x[::2])
print(x[1:3])
print(x[::-1])
print(x[::-2])

[4 3 5 2 6 7]
[4 3 5]
[5 2 6 7]
[4 5 6]
[3 5]
[7 6 2 5 3 4]
[7 2 3]


In [10]:
# 2D array slicing
x=np.array([[2,3,1],[6,7,8]])
print(x)
print()
print(x[0,::])

[[2 3 1]
 [6 7 8]]

[2 3 1]


In [11]:
# 2D array slicing
x=np.array([[2,3,1],[6,7,8]])
print(x)
print()
print(x[1,::])

[[2 3 1]
 [6 7 8]]

[6 7 8]


In [12]:
# 2D array slicing
x=np.array([[2,3,1],[6,7,8]])
print(x)
print()
print(x[0,::-1])

[[2 3 1]
 [6 7 8]]

[1 3 2]


In [13]:
# 3D array slicing
x=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
print(x)
print()
print(x[1,1,1:])

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]

[14 15 16]


In [14]:
# 3D array slicing
x=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
print(x)
print()
print(x[0,1,::-1])

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]

[8 7 6 5]
