# iterating numpy arrays

In [1]:
# 1D array
import numpy as np
x=np.array([1,4,2,5,6,8])
print(x)
print()
for i in x:
    print(i)

[1 4 2 5 6 8]

1
4
2
5
6
8


In [2]:
# 2D array
x=np.array([[2,3,4],[5,6,7]])
print(x)
print()
for i in x:
    print(i)

[[2 3 4]
 [5 6 7]]

[2 3 4]
[5 6 7]


In [6]:
# 2D array
x=np.array([[2,3,4],[5,6,7]])
print(x)
print()
for i in x:
    for j in i:
        print(j)

     


[[2 3 4]
 [5 6 7]]

2
3
4
5
6
7


In [7]:
# 3D arrays
x=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(x)
print()
for i in x:
    for j in i:
        for k in j:
            print(k)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]

1
2
3
4
5
6
1
2
3
4
5
6


# np.nditer(variableName)

In [8]:
# 3D arrays
x=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(x)
print()
for i in np.nditer(x):
    print(i)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]

1
2
3
4
5
6
1
2
3
4
5
6


In [9]:
# 3D arrays with np.ndenumerate() for print index and value
x=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(x)
print()
for i,d in np.ndenumerate(x):
    print(i,d)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(1, 0, 0) 1
(1, 0, 1) 2
(1, 0, 2) 3
(1, 1, 0) 4
(1, 1, 1) 5
(1, 1, 2) 6


In [10]:
# 2D arrays with np.ndenumerate() for print index and value
x=np.array([[1,2,3],[5,6,7]])
print(x)
print()
for i,d in np.ndenumerate(x):
    print(i,d)

[[1 2 3]
 [5 6 7]]

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 5
(1, 1) 6
(1, 2) 7
