# joining and split

# concatenate() for joining

In [1]:
# 1D Arrays joining
import numpy as np
x1=np.array([1,2,3,4,5])
x2=np.array([2,3,4,5,6])
x=np.concatenate((x1,x2))
print(x)

[1 2 3 4 5 2 3 4 5 6]


In [2]:
# 2D arrays joining
import numpy as np
x1=np.array([[1,2],[3,4]])
x2=np.array([[5,6],[7,8]])
x=np.concatenate((x1,x2),axis=1) # axis=1 means row side merged
print(x1)
print()
print(x2)
print()
print(x)

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[1 2 5 6]
 [3 4 7 8]]


In [3]:
# 2D arrays joining
import numpy as np
x1=np.array([[1,2],[3,4]])
x2=np.array([[5,6],[7,8]])
x=np.concatenate((x1,x2),axis=0) # axis=0 means column side merged
print(x1)
print()
print(x2)
print()
print(x)

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


# stack() for joining

In [4]:
# horizontaly
x1=np.array([1,2,3,4])
x2=np.array([5,6,7,8])
print(x1)
print()
print(x2)
print()
x=np.hstack((x1,x2))
print(x)

[1 2 3 4]

[5 6 7 8]

[1 2 3 4 5 6 7 8]


In [5]:
# verticaly
x1=np.array([1,2,3,4])
x2=np.array([5,6,7,8])
x=np.vstack((x1,x2))
print(x1)
print()
print(x2)
print()
print(x)

[1 2 3 4]

[5 6 7 8]

[[1 2 3 4]
 [5 6 7 8]]


In [6]:
# height
x1=np.array([1,2,3,4])
x2=np.array([5,6,7,8])
x=np.dstack((x1,x2))
print(x1)
print()
print(x2)
print()
print(x)

[1 2 3 4]

[5 6 7 8]

[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]


# split ()

In [7]:
# 1D array_split(variable,partisionNumber)
x=np.array([1,2,3,4,5,6])
print(x)
print()
x1=np.array_split(x,3)
print(x1)


[1 2 3 4 5 6]

[array([1, 2]), array([3, 4]), array([5, 6])]


In [8]:
# 1D array_split(variable,partisionNumber)
x=np.array([1,2,3,4,5,6])
print(x)
print()
x1=np.array_split(x,3)
print(x1)
print()
print(x1[0])
print(x1[1])
print(x1[2])

[1 2 3 4 5 6]

[array([1, 2]), array([3, 4]), array([5, 6])]

[1 2]
[3 4]
[5 6]


In [9]:
# 2D array_split
x=np.array([[1,2],[3,4],[5,6]])
print(x)
print()
x1=np.array_split(x,3)
print(x1)


[[1 2]
 [3 4]
 [5 6]]

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]
