# search array

In [1]:
import numpy as np
x=np.array([2,5,8,3,4,5,3,2,5])
x1=np.where(x==5)
print(x1)

(array([1, 5, 8], dtype=int64),)


In [2]:
import numpy as np
x=np.array([2,5,8,3,4,5,3,2,5])
x1=np.where(x==3)
print(x1)

(array([3, 6], dtype=int64),)


In [3]:
import numpy as np
x=np.array([2,5,8,3,4,5,3,2,5])
x1=np.where(x==2)
print(x1)

(array([0, 7], dtype=int64),)


In [4]:
import numpy as np
x=np.array([2,5,8,3,4,5,3,2,5])
x1=np.where(x!=5)
print(x1)

(array([0, 2, 3, 4, 6, 7], dtype=int64),)


In [5]:
import numpy as np
x=np.array([2,5,8,3,4,5,3,2,5])
x1=np.where(x%2==0) # even
print(x1)

(array([0, 2, 4, 7], dtype=int64),)


In [ ]:
import numpy as np
x=np.array([2,5,8,3,4,5,3,2,5])
x1=np.where(x%2!=0) # even
print(x1)

# sort array

In [6]:
x=np.array([4,3,5,7,9,1,4,5,9,7,3])
x1=np.sort(x)
print(x)
print()
print(x1)

[4 3 5 7 9 1 4 5 9 7 3]

[1 3 3 4 4 5 5 7 7 9 9]


In [7]:
#2D array sorting
x=np.array([[4,3,2,6,4],[9,2,5,1,6]])
x1=np.sort(x)
print(x)
print()
print(x1)

[[4 3 2 6 4]
 [9 2 5 1 6]]

[[2 3 4 4 6]
 [1 2 5 6 9]]


# Filter array

In [8]:
x=np.array(['a','b','k','d'])
f=[True,False,False,True] # making list
x1=x[f]
print(x1)
print(type(x1))

['a' 'd']
<class 'numpy.ndarray'>
