# shuffle

In [5]:
import numpy as np
x=np.array([1,2,3,4,5,6])
np.random.shuffle(x)
print(x)

[2 3 5 1 4 6]


# unique

In [6]:
x=np.array([1,2,3,4,2,5,2,7])
x1=np.unique(x)
print(x)
print()
print(x1)

[1 2 3 4 2 5 2 7]

[1 2 3 4 5 7]


In [7]:
x=np.array([1,2,3,4,2,5,2,7])
x1=np.unique(x,return_index=True)

print(x1)

(array([1, 2, 3, 4, 5, 7]), array([0, 1, 2, 3, 5, 7], dtype=int64))


In [8]:
x=np.array([1,2,3,4,2,5,2,7])
x1=np.unique(x,return_index=True,return_counts=True)

print(x1)

(array([1, 2, 3, 4, 5, 7]), array([0, 1, 2, 3, 5, 7], dtype=int64), array([1, 3, 1, 1, 1, 1], dtype=int64))


# resize

In [9]:
x=np.array([1,2,3,4,5,6])
y=np.resize(x,(2,3))
print(y)


[[1 2 3]
 [4 5 6]]


In [10]:
x=np.array([1,2,3,4,5,6,7,8,9])
y=np.resize(x,(3,3))
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
x=np.array([1,2,3,4,5,6])
y=np.resize(x,(3,2))
print(y)

[[1 2]
 [3 4]
 [5 6]]


# flatten

In [12]:
x=np.array([1,2,3,4,5,6])
y=np.resize(x,(3,2)) # this is 2D array 
z=y.flatten() # converted 1D array
print(z)

[1 2 3 4 5 6]
