# numpy insert array

In [1]:
import numpy as np
x=np.array([1,2,3,4])
print(x)
x1=np.insert(x,2,40) # arrayName,Position,Value
print(x1)


[1 2 3 4]
[ 1  2 40  3  4]


In [2]:
import numpy as np
x=np.array([1,2,3,4])
print(x)
x1=np.insert(x,(2,4),40) # arrayName,Position,Value
print(x1)

[1 2 3 4]
[ 1  2 40  3  4 40]


In [3]:
# 2D array
x=np.array([[1,2,3,4],[5,6,7,8]])
x1=np.insert(x,2,10,axis=0)
print(x1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [10 10 10 10]]


In [4]:
# 2D array
x=np.array([[1,2,3,4],[5,6,7,8]])
x1=np.insert(x,2,10,axis=1)
print(x1)

[[ 1  2 10  3  4]
 [ 5  6 10  7  8]]


# delete array

In [5]:
import numpy as np
x=np.array([1,2,3,4])
print(x)
print()
d=np.delete(x,2) # varNmame , Position(values index)
print(d)

[1 2 3 4]

[1 2 4]
