# Matrix in Numpy

In [4]:
# matrix
import numpy as np
x=np.matrix([[1,2,3],[1,2,3]])
print(x)
print(type(x))

[[1 2 3]
 [1 2 3]]
<class 'numpy.matrix'>


In [5]:
# array
import numpy as np
x=np.array([[1,2,3],[1,2,3]])
print(x)
print(type(x))

[[1 2 3]
 [1 2 3]]
<class 'numpy.ndarray'>


In [10]:
# arithmetic operation
x1=np.matrix([[1,2,3],[4,5,6]])
x2=np.matrix([[7,8,9],[7,8,9]])
print(x1)
print()
print(x2)
print()
x=x1+x2
print(x)


[[1 2 3]
 [4 5 6]]

[[7 8 9]
 [7 8 9]]

[[ 8 10 12]
 [11 13 15]]


In [11]:
x1=np.matrix([[1,2,3],[4,5,6]])
x2=np.matrix([[7,8,9],[7,8,9]])
print(x1)
print()
print(x2)
print()
x=x1-x2
print(x)

[[1 2 3]
 [4 5 6]]

[[7 8 9]
 [7 8 9]]

[[-6 -6 -6]
 [-3 -3 -3]]


In [15]:
# matrix multiplication
x1=np.matrix([[1,2],[4,5]])
x2=np.matrix([[7,8],[7,8]])
print(x1)
print()
print(x2)
print()

print(x1.dot(x2))

[[1 2]
 [4 5]]

[[7 8]
 [7 8]]

[[21 24]
 [63 72]]


# matrix function

# transpose

In [16]:
x=np.matrix([[1,2,3],[4,5,6]])
print(x)
print()

x1=np.transpose(x)
print(x1)

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]


# Swapaxes

In [19]:
x=np.matrix([[1,2,3],[4,5,6]])
print(x)
print()

x1=np.swapaxes(x,0,1)
print(x1)

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]


# inverse

In [24]:
x=np.matrix([[1,2],[4,5]])
print(x)
print()
x1=np.linalg.inv(x)
print(x1)

[[1 2]
 [4 5]]

[[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]


# power